[project]
name = "yk-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.129.0",
    "ipywidgets>=8.1.8",
    "langchain>=1.2.10",
    "langchain-openai>=1.1.9",
    "langgraph>=1.0.8",
    "langgraph-api>=0.7.37",
    "langgraph-cli[inmem]>=0.4.12",
    "mcp>=1.26.0",
    "tavily>=1.1.0",
]
