[project]
name = "yk-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[all]>=0.128.3",
    "google-generativeai>=0.8.6",
    "langchain>=1.2.9",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.1",
    "langchain-openai>=1.1.7",
    "openai>=2.17.0",
    "scalar-fastapi>=1.6.1",
    "sqlmodel>=0.0.32",
    "streamlit>=1.54.0",
]
