[project]
name = "yk-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.128.3",
    "google-generativeai>=0.8.6",
    "ipywidgets>=8.1.8",
    "langchain>=1.2.9",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.1",
    "langchain-openai>=1.1.7",
    "langgraph[cli]>=1.0.8",
    "langsmith[openai-agents]>=0.6.9",
    "openai>=2.17.0",
    "scalar-fastapi>=1.6.1",
    "sqlmodel>=0.0.32",
    "streamlit>=1.54.0",
    "tavily>=1.1.0",
]
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["app", "langchain"]
